language: php

matrix:
  include:
    - env: DBTYPE=mysql; MW=1.27.0
      php: 5.5
    - env: DBTYPE=sqlite; MW=1.28.0
      php: 7.0
    - env: DBTYPE=mysql; MW=master
      php: 7.1

sudo: false

before_install:
  - travis_retry composer self-update
  - bash .travis.install.sh

install: travis_retry composer install

sscript: ../phase3/tests/phpunit/phpunit.php -c ../phase3/extensions/ParserHooks/phpunit.xml.dist

after_success:
  - if [[ "`phpenv version-name`" != "7.1" ]]; then exit 0; fi
  - ../phase3/tests/phpunit/phpunit.php -c ../phase3/extensions/ParserHooks/phpunit.xml.dist --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
